print("hello fams")
print("anime is live")
print("jangan lupa turu")
print("jangan makan sambil makan")
print("ko kamu kaya kasurman")
print("gabisa nafas tanpa oksigen")
print("jangan cari yang gaada")
print("absurd humor m4")
print("Kebodohan adalah temaku, biarlah satir menjadi laguku")
print("thanks")